DROP TABLE IF EXISTS CF_WidgetUsuario;
DROP TABLE IF EXISTS CF_DashboardFavorito;
DROP TABLE IF EXISTS CF_NotificacionUsuario;
DROP TABLE IF EXISTS CF_Notificacion;
DROP TABLE IF EXISTS CF_Alerta;
DROP TABLE IF EXISTS CF_KPI;
